### ISSUE TITLE
jest fail on ExmapleTest

### ISSUE THREAD

**Issue by guileen** [guileen/react-forum#2]
Example.js

``` jsx
class Example extends Component {
  render() {
    return <div></div>
  }
}
```

ExampleTest.js

``` js
    var example = TestUtils.renderIntoDocument(
        <Example title="hello"/>
    )
```

jest output:

```
 Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
        at invariant (node_modules/fbjs/lib/invariant.js:39:15)
        at instantiateReactComponent [as _instantiateReactComponent] (node_modules/react/lib/instantiateReactComponent.js:64:134)
        at ReactCompositeComponentMixin.mountComponent (node_modules/react/lib/ReactCompositeComponent.js:223:36)
        at wrapper [as mountComponent] (node_modules/react/lib/ReactPerf.js:66:21)
        at Object.ReactReconciler.mountComponent (node_modules/react/lib/ReactReconciler.js:37:35)
        at mountComponentIntoNode (node_modules/react/lib/ReactMount.js:266:32)
        at ReactReconcileTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:136:20)
        at batchedMountComponentIntoNode (node_modules/react/lib/ReactMount.js:282:15)
        at ReactDefaultBatchingStrategyTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:136:20)
        at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
        at Object.batchedUpdates (node_modules/react/lib/ReactUpdates.js:94:20)
        at Object.ReactMount._renderNewRootComponent (node_modules/react/lib/ReactMount.js:476:18)
        at Object.wrapper [as _renderNewRootComponent] (node_modules/react/lib/ReactPerf.js:66:21)
        at Object.ReactMount._renderSubtreeIntoContainer (node_modules/react/lib/ReactMount.js:550:32)
        at Object.ReactMount.render (node_modules/react/lib/ReactMount.js:570:23)
        at Object.wrapper [as render] (node_modules/react/lib/ReactPerf.js:66:21)
        at Object.ReactTestUtils.renderIntoDocument (node_modules/react/lib/ReactTestUtils.js:76:21)
        at Spec.eval (js/components/__tests__/ExampleTest.js:10:50)
```

**Comment by guileen** [comment]
use mocha karma instead.`
